[package]
name = "digit_recognition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.27"
mnist = "0.5"
ndarray = "0.15.6"
rand = "0.8.5"
reqwest = "0.11.20"
